theme: jekyll-theme-hacker
google_analytics: UA-xxxxxx-x

plugins:
  - jekyll-sitemap
  
google_analytics: UA-....

sitemap:
    path: sitemap.xml
    template: ./sitemap_template.xml
    rel: false


